[package]
name = "lzf"
version = "0.3.1"
authors = ["Jan-Erik Rediger <badboy@fnordig.de>"]
keywords = ["compression"]
description = "A small wrapper around LibLZF, a very small data compression library"
homepage = "https://github.com/badboy/lzf-rs"
documentation = "http://badboy.github.io/lzf-rs/"
license = "BSD-3-Clause"
readme = "README.md"

include = [
  "README.md",
  "LICENSE",
  "Cargo.toml",
  "src/**/*",
  "benches/**/*",
  "examples/**/*"
]

[dependencies]
clippy = {version = "*", optional = true}
quickcheck = {version = "0.2", optional = true}

[features]
default = []
